@startuml
skinparam defaultTextAlignment left


state HEATING_STATE_OFF
state HEATING_STATE_ON
state HEATING_STATE_INHIBIT

[*] --> HEATING_STATE_OFF

HEATING_STATE_OFF --> HEATING_STATE_ON

state HEATING_STATE_ON{
  state HEATING_STATE_WAIT
  state HEATING_STATE_HEAT

  [*] --> HEATING_STATE_WAIT

  HEATING_STATE_WAIT --> HEATING_STATE_HEAT
  HEATING_STATE_HEAT --> HEATING_STATE_WAIT

}
HEATING_STATE_ON --> HEATING_STATE_OFF



@enduml