@startuml
skinparam defaultTextAlignment left

state PINCODE_INIT
state PINCODE_WAIT_CODE
state PINCODE_CHECK_CODE
state PINCODE_TIMEOUT
state PINCODE_CODE_OK_MASTER
state PINCODE_CODE_OK_USER
state PINCODE_REINIT
state PINCODE_CODE_ERROR
state PINCODE_CODE_LOCKED


[*] --> PINCODE_INIT
PINCODE_INIT -down-> PINCODE_WAIT_CODE : init_done

PINCODE_WAIT_CODE -right-> PINCODE_TIMEOUT
PINCODE_WAIT_CODE -down-> PINCODE_CHECK_CODE

PINCODE_TIMEOUT -up-> PINCODE_INIT

PINCODE_CHECK_CODE --> PINCODE_CODE_OK_MASTER
PINCODE_CHECK_CODE --> PINCODE_CODE_OK_USER
PINCODE_CHECK_CODE -> PINCODE_CODE_ERROR
PINCODE_CHECK_CODE --> PINCODE_WAIT_CODE

PINCODE_CODE_ERROR --> PINCODE_CODE_LOCKED
PINCODE_CODE_ERROR --> PINCODE_REINIT

PINCODE_CODE_LOCKED --> PINCODE_REINIT

@enduml