name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '9-2019-q4' # The arm-none-eabi-gcc release to use.
    - name: make
      run: make
    - name: test
      run: make test
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: out/tests/*.xml